-- FATURAMENTO

SELECT
    SUM(FATO_VENDA.VALOR_VENDA) AS Faturamento
FROM
    FATO_VENDA
JOIN
    DIM_CANCELAMENTO ON FATO_VENDA.ID_CANCELAMENTO = DIM_CANCELAMENTO.ID_CANCELAMENTO 
WHERE
    DIM_CANCELAMENTO.CANCELAMENTO <> 'Cancelado';

-- QTD CLIENTES

SELECT
    COUNT(DISTINCT DIM_CLIENTE.REGISTRO_CLIENTE) AS QtdClientes
FROM
   DIM_CLIENTE
JOIN
    DIM_CANCELAMENTO ON DIM_CLIENTE.ID_CLIENTE = DIM_CANCELAMENTO.ID_CANCELAMENTO
WHERE
    DIM_CANCELAMENTO.CANCELAMENTO <> 'Cancelado';
    
-- TICKET MÉDIO 
    
-- CTE (Common Table Expression) para calcular o faturamento
WITH FaturamentoCTE AS (
    SELECT
        SUM(FATO_VENDA.VALOR_VENDA) AS Faturamento
    FROM
        FATO_VENDA
    JOIN
        DIM_CANCELAMENTO ON FATO_VENDA.ID_CANCELAMENTO = DIM_CANCELAMENTO.ID_CANCELAMENTO 
    WHERE
        DIM_CANCELAMENTO.CANCELAMENTO <> 'Cancelado'
)

-- CTE para calcular a quantidade de clientes
, QtdClientesCTE AS (
    SELECT
        COUNT(DISTINCT DIM_CLIENTE.REGISTRO_CLIENTE) AS QtdClientes
    FROM
       DIM_CLIENTE
    JOIN
        DIM_CANCELAMENTO ON DIM_CLIENTE.ID_CLIENTE = DIM_CANCELAMENTO.ID_CANCELAMENTO
    WHERE
        DIM_CANCELAMENTO.CANCELAMENTO <> 'Cancelado'
)

-- Consulta principal para calcular o ticket médio
SELECT
    FaturamentoCTE.Faturamento / QtdClientesCTE.QtdClientes AS TicketMedio
FROM
    FaturamentoCTE, QtdClientesCTE;

-- QTD SELLER

SELECT
    COUNT(DISTINCT DIM_SELLER.SELLER) AS QtdSeller
FROM
   DIM_SELLER
JOIN
    DIM_CANCELAMENTO ON DIM_SELLER.ID_SELLER = DIM_CANCELAMENTO.ID_CANCELAMENTO
WHERE
    DIM_CANCELAMENTO.CANCELAMENTO <> 'Cancelado';
    
-- QTD CANCELAMENTOS

SELECT
    COUNT(*) AS QtdCancelamentos
FROM
   DIM_CANCELAMENTO
WHERE
    DIM_CANCELAMENTO.CANCELAMENTO = 'Cancelado';
    
-- VALOR CANCELAMEMTO

SELECT
    SUM(FATO_VENDA.VALOR_VENDA) AS ValorCancelamento
FROM
    FATO_VENDA
JOIN
    DIM_CANCELAMENTO ON FATO_VENDA.ID_CANCELAMENTO = DIM_CANCELAMENTO.ID_CANCELAMENTO 
WHERE
    DIM_CANCELAMENTO.CANCELAMENTO = 'Cancelado';

-- TOTAL PEDIDOS

SELECT
    COUNT(*) AS TotalPedidos
FROM
   FATO_VENDA
WHERE
    FATO_VENDA.VALOR_VENDA IS NOT NULL;
    
-- QTD CATEGORIAS

SELECT
    COUNT(DISTINCT DIM_PRODUTO.CATEGORIA_PRODUTO) AS QtdCategorias
FROM
   DIM_PRODUTO
JOIN
    DIM_CANCELAMENTO ON DIM_PRODUTO.ID_PRODUTO = DIM_CANCELAMENTO.ID_CANCELAMENTO
WHERE
    DIM_CANCELAMENTO.CANCELAMENTO <> 'Cancelado';
    
-- MEDIA AVALIAÇÃO 

SELECT
    AVG(CAST(Personalizar AS FLOAT)) AS MediaPersonalizada
FROM (
    SELECT
        AVALIACAO,
        CASE
            WHEN AVALIACAO = 'nenhum' THEN 0
            WHEN AVALIACAO = 'Péssimo' THEN 0
            WHEN AVALIACAO = 'Ruim' THEN 2
            WHEN AVALIACAO = 'Mediano' THEN 3
            WHEN AVALIACAO = 'Bom' THEN 4
            WHEN AVALIACAO = 'Excelente' THEN 0
            ELSE NULL
        END AS Personalizar
    FROM
        DIM_AVALIACAO
) AS Subquery
WHERE
    Personalizar <> 0;
    



    
    
