DROP TABLE if exists dados_shopnow;

CREATE TABLE dados_shopnow (

  `DATA_PEDIDO` VARCHAR(255) NULL,
  `CATEGORIA_PRODUTO` VARCHAR(255) NULL,
  `PRODUTO` VARCHAR(255) NULL,
  `QTD_PRODUTO` INT NULL,
  `VALOR_VENDA` INT NULL,
  `FORMA_PAGAMENTO` VARCHAR(255) NULL,
  `DATA_ENTREGA` VARCHAR(255) NULL,
  `TIPO_CLIENTE` VARCHAR(255) NULL,
  `REGISTRO_CLIENTE` INT NULL,
  `PAIS_CLIENTE` VARCHAR(255) NULL,
  `ESTADO_CLIENTE` VARCHAR(255) NULL,
  `CIDADE_CLIENTE` VARCHAR(255) NULL,
  `CEP_CLIENTE` VARCHAR(255) NULL,
  `LATITUDE_CLIENTE` VARCHAR(255) NULL,
  `LONGITUDE_CLIENTE` VARCHAR(255) NULL,
  `SELLER` VARCHAR(255) NULL,
  `FORNECEDOR` VARCHAR(255) NULL,
  `CANCELAMENTO` VARCHAR(255) NULL,
  `MOTIVO_CANCELAMENTO` VARCHAR(255) NULL,
  `TIPO_ENTREGA` VARCHAR(255) NULL,
  `CANAL_VENDA` VARCHAR(255) NULL,
  `AVALIACAO` VARCHAR(255) NULL,
  `COMISSAO` VARCHAR(255) NULL);

SELECT *
FROM dados_shopnow LIMIT 3;
# SELECT count(*)
# FROM dados_shopnow;

load data infile '/var/lib/mysql-files/dados_shopnow_2.csv' 
into table dados_shopnow
fields terminated by ',' enclosed by '"'
LINES TERMINATED BY '\n'
ignore 1 rows;

 SELECT count(*)
FROM dados_shopnow;

ALTER TABLE dados_shopnow
ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY;

