
-- Populando tabelas fato e dimensão

INSERT INTO DIM_AVALIACAO (AVALIACAO, ID_SHOPNOW)
SELECT AVALIACAO, ID
FROM dados_shopnow;

INSERT INTO DIM_CANAL_VENDA (CANAL_VENDA, ID_SHOPNOW)
SELECT CANAL_VENDA, ID
FROM dados_shopnow;

INSERT INTO DIM_CANCELAMENTO (CANCELAMENTO, MOTIVO_CANCELAMENTO, ID_SHOPNOW)
SELECT CANCELAMENTO, MOTIVO_CANCELAMENTO, ID
FROM dados_shopnow;

INSERT INTO DIM_CLIENTE (PAIS,ESTADO,CIDADE,CEP,LATITUDE,LONGITUDE, ID_SHOPNOW,REGISTRO_CLIENTE)
SELECT PAIS_CLIENTE,ESTADO_CLIENTE,CIDADE_CLIENTE,CEP_CLIENTE,LATITUDE_CLIENTE,LONGITUDE_CLIENTE, ID, REGISTRO_CLIENTE
FROM dados_shopnow;

INSERT INTO DIM_ENTREGA (DATA_ENTREGA, ANO, MES, DIA, DIA_SEMANA, TIPO_ENTREGA, ID_SHOPNOW)
SELECT
    DATA_ENTREGA,
    YEAR(DATA_ENTREGA) AS ANO,
    MONTH(DATA_ENTREGA) AS MES,
    DAY(DATA_ENTREGA) AS DIA,
    CASE DAYOFWEEK(DATA_ENTREGA)
        WHEN 1 THEN 'Domingo'
        WHEN 2 THEN 'Segunda-feira'
        WHEN 3 THEN 'Terça-feira'
        WHEN 4 THEN 'Quarta-feira'
        WHEN 5 THEN 'Quinta-feira'
        WHEN 6 THEN 'Sexta-feira'
        WHEN 7 THEN 'Sábado'
    END AS DIA_SEMANA,
    TIPO_ENTREGA,
    ID
FROM dados_shopnow 
WHERE DATA_ENTREGA IS NOT NULL;

INSERT INTO DIM_FORNECEDOR (FORNECEDOR, ID_SHOPNOW)
SELECT FORNECEDOR, ID
FROM dados_shopnow;

INSERT INTO DIM_MEIO_PAGAMENTO (MEIO_PAGAMENTO, ID_SHOPNOW)
SELECT FORMA_PAGAMENTO, ID
FROM dados_shopnow;

INSERT INTO DIM_PEDIDO (DATA_PEDIDO, ANO, MES, DIA, DIA_SEMANA, ID_SHOPNOW)
SELECT
    DATA_PEDIDO,
    YEAR(DATA_PEDIDO) AS ANO,
    MONTH(DATA_PEDIDO) AS MES,
    DAY(DATA_PEDIDO) AS DIA,
    CASE DAYOFWEEK(DATA_PEDIDO)
        WHEN 1 THEN 'Domingo'
        WHEN 2 THEN 'Segunda-feira'
        WHEN 3 THEN 'Terça-feira'
        WHEN 4 THEN 'Quarta-feira'
        WHEN 5 THEN 'Quinta-feira'
        WHEN 6 THEN 'Sexta-feira'
        WHEN 7 THEN 'Sábado'
    END AS DIA_SEMANA,
    ID
FROM dados_shopnow;

INSERT INTO DIM_PRODUTO (CATEGORIA_PRODUTO, PRODUTO, ID_SHOPNOW)
SELECT CATEGORIA_PRODUTO, PRODUTO, ID
FROM dados_shopnow;

INSERT INTO DIM_SELLER (SELLER, ID_SHOPNOW)
SELECT SELLER, ID
FROM dados_shopnow;

INSERT INTO DIM_TIPO_CLIENTE(TIPO_CLIENTE, ID_SHOPNOW)
SELECT TIPO_CLIENTE, ID
FROM dados_shopnow;


 INSERT INTO FATO_VENDA(
            VALOR_VENDA,
            COMISSAO,
            QTD_PRODUTO,
            ID_FORNECEDOR,
            ID_CLIENTE,
            ID_PEDIDO,
            ID_PRODUTO,
            ID_SELLER,
            ID_CANAL_VENDA,
            ID_AVALIACAO,
            ID_MEIO_PAGAMENTO,
            ID_ENTREGA,
            ID_CANCELAMENTO,
            ID_TIPO_CLIENTE
            )
            
SELECT
	dados_shopnow.VALOR_VENDA,
    dados_shopnow.COMISSAO,
    dados_shopnow.QTD_PRODUTO,
    DIM_FORNECEDOR.ID_FORNECEDOR,
    DIM_CLIENTE.ID_CLIENTE,
    DIM_PEDIDO.ID_PEDIDO,
    DIM_PRODUTO.ID_PRODUTO,
    DIM_SELLER.ID_SELLER,
    DIM_CANAL_VENDA.ID_CANAL_VENDA,
    DIM_AVALIACAO.ID_AVALIACAO,
    DIM_MEIO_PAGAMENTO.ID_MEIO_PAGAMENTO,
    DIM_ENTREGA.ID_ENTREGA,
    DIM_CANCELAMENTO.ID_CANCELAMENTO,
    DIM_TIPO_CLIENTE.ID_TIPO_CLIENTE
FROM dados_shopnow
	INNER JOIN DIM_AVALIACAO ON DIM_AVALIACAO.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_CANAL_VENDA ON DIM_CANAL_VENDA.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_CANCELAMENTO ON DIM_CANCELAMENTO.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_CLIENTE ON DIM_CLIENTE.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_ENTREGA ON DIM_ENTREGA.ID_SHOPNOW = dados_shopnow.ID
	INNER JOIN DIM_FORNECEDOR ON DIM_FORNECEDOR.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_MEIO_PAGAMENTO ON DIM_MEIO_PAGAMENTO.ID_SHOPNOW = dados_shopnow.ID
	INNER JOIN DIM_PEDIDO ON DIM_PEDIDO.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_PRODUTO ON DIM_PRODUTO.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_SELLER ON DIM_SELLER.ID_SHOPNOW = dados_shopnow.ID
    INNER JOIN DIM_TIPO_CLIENTE ON DIM_TIPO_CLIENTE.ID_SHOPNOW = dados_shopnow.ID;
    #LIMIT 10;





    
   




ALTER TABLE DIM_AVALIACAO DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_CANAL_VENDA DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_CANCELAMENTO DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_CLIENTE DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_ENTREGA DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_FORNECEDOR DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_MEIO_PAGAMENTO DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_PEDIDO DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_PRODUTO DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_SELLER DROP COLUMN ID_SHOPNOW;
ALTER TABLE DIM_TIPO_CLIENTE DROP COLUMN ID_SHOPNOW;
ALTER TABLE FATO_VENDA DROP COLUMN ID_SHOPNOW;